export const colors = (colorScheme = "light") => ({
  background: colorScheme === "dark" ? "#1e1e1e" : "#f5f5f5",
  card: colorScheme === "dark" ? "#2a2a2a" : "#ffffff",
  textPrimary: colorScheme === "dark" ? "#f5f5f5" : "#1e1e1e",
  textSecondary: colorScheme === "dark" ? "#aaaaaa" : "#666666",
  accent: "#2563eb",
  myBubble: "#2563eb",
  myText: "#fff",
  otherBubble: colorScheme === "dark" ? "#2a2a2a" : "#e5e5e5",
  otherText: colorScheme === "dark" ? "#e5e5e5" : "#1e1e1e",
  timeText: colorScheme === "dark" ? "#bbb" : "#666",
  inputWrapper: colorScheme === "dark" ? "#1a1a1a" : "#f0f0f0",
  inputBox: colorScheme === "dark" ? "#2a2a2a" : "#ffffff",
  inputText: colorScheme === "dark" ? "#fff" : "#1e1e1e",
  sendBtn: "#2563eb",
  sendText: "#fff",
  headerBackground: colorScheme === "dark" ? "#1e1e1e" : "#4a90e2",
  border: colorScheme === "dark" ? "#333" : "#ccc",
  avatarBackground: "#444",
  online: "#4ade80",
  offline: "#999",
});
